source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'NHMapViewController_Example', :exclusive => true do
  pod "NHMapViewController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "NHMapViewController", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
